### ISSUE TITLE
Insert emoji by typing in characters, without needing to open popup

### ISSUE THREAD

**Issue by HimanshuSojitra** [lbertenasco/ng-emoji-picker#10]
Is inserting emojis by typing in corresponding characters supported?
Example: user enters `:smile:` or `:)` in the input box and the text gets replaced by the corresponding emoji.

Thank you!

**Comment by lbertenasco** [comment]
Hi @HimanshuSojitra !
This works: `:smile:` -> 😄  
This does not: `:)`
😉
