### ISSUE TITLE
Styling and Placeholder support for Emoji Input

### ISSUE THREAD

**Issue by HimanshuSojitra** [lbertenasco/ng-emoji-picker#11]
Is there a way I can add a class to or inline style the emoji text input?
I would also like to add a placeholder to the input.
Is it something already supported?

Thank you! :)

**Comment by lbertenasco** [comment]
Hi @HimanshuSojitra !
No, it is not supported, you can check out the component here: https://github.com/lbertenasco/ng-emoji-picker/blob/master/src/emoji-input/emoji-input.component.ts
And feel free to create a PR if you want to add more functionality :)
