### ISSUE TITLE
Not possible to apply a class on the input element

### ISSUE THREAD

**Issue by h3llrais3r** [lbertenasco/ng-emoji-picker#12]
Hi, Thanks for your support for the ng-emoji-picker, but I see that it's not possible to apply a class on the input element.
Example:
```
<emoji-input [(model)]="messageWithEmoji" class="form-control" style="display: inline-block;" (onEnter)="onEnter()" (click)="openPopup(false)" (setPopupAction)="setPopupAction($event)"></emoji-input>
```
This applies the style on ```<emoji-input>``` element, not on the nested ```<input>``` element.

![image](https://user-images.githubusercontent.com/1945295/34815106-6de77676-f6b0-11e7-9a07-4054abb4d9e9.png)

Can you provide a ```class="..."``` option so it' can be applied on the internal input element? (same when using a textarea)

**Comment by lbertenasco** [comment]
Just released version `1.2.1` can you try that out?
Added:
```
  @Input() inputClass = '';
  @Input() searchClass = '';
```

**Comment by h3llrais3r** [comment]
Thanks, it works for the inputClass but for some kind of reason it doesn't seem to take my searchClass unless I'm using again /deep/.
Any idea?

**Comment by lbertenasco** [comment]
I'll debug this today and let you know.
Glad at least 1 of them is working 😅

**Comment by zamananjum0** [comment]
Please deploy the demo of this module.

**Comment by Amber711** [comment]
@lbertenasco @h3llrais3r Hi, i am running into the same problem. Did any of you ever figure it out?... thanks

**Comment by h3llrais3r** [comment]
@Amber711 Version 1.2.1 partially fixes the problem.
The only thing that is left is the styling of the dropdown that still needs the `/deep/` in order to get it styled.
@lbertenasco still needs to investigate this one.

**Comment by lbertenasco** [comment]
Hi @h3llrais3r
Please use the `searchClass ` as an input:

`[searchClass]="myCustomClass"`

`this.myCustomClass = 'red-background';`

Hi @Amber711 What seems to be your issue? Can you add more information? Thanks!

BTW: I created a demo project, so feel free to check that out :)
https://github.com/lbertenasco/ng-emoji-picker-demo

**Comment by Amber711** [comment]
@lbertenasco @h3llrais3r  hi guys!  As @h3llrais3r indicated, we just need to added /deep/ in order to style the dropdown.  I am trying to bind the onEnter event to the emoji-input, but got no response after hitting the enter key. did you guys ever try that one too? Thank you so much for your help!!! : )
