### ISSUE TITLE
Emoji inserted only at the end of the text

### ISSUE THREAD

**Issue by turbo5** [lbertenasco/ng-emoji-picker#14]
Even if the cursor is inside the text (mid-word for example), the chosen emoji gets inserted after the last character in the input/textbox.
Is there any chance for this improvement (bugfix?) ?

**Comment by SebastianGiro** [comment]
@turbo5 I think I can make it happen this weekend.

**Comment by turbo5** [comment]
That would be perfect!

**Comment by turbo5** [comment]
Hi! Any advancements, or perhaps some advice/help you need?

**Comment by SebastianGiro** [comment]
@turbo5 would be merged soon :)

**Comment by lbertenasco** [comment]
Hi @turbo5,
Please install `ng-emoji-picker@1.2.3`

**Comment by turbo5** [comment]
So far so good! Thanks a lot, we gonna give it a test run, gonna tell you if we find anything.
