### ISSUE TITLE
Issue with Angular 5

### ISSUE THREAD

**Issue by Johndeep3580** [lbertenasco/ng-emoji-picker#16]
I have followed your documentation to add emoji picker to my Angular 5 app but somehow only input field is displayed and no emoji picker is shown.

I have also raised a question on stackoverflow:
[https://stackoverflow.com/questions/49474410/how-to-use-angular-4-emoji-picker]() 
but my issue has not be resolved yet.Kindly help me out

**Comment by lbertenasco** [comment]
Hi @Johndeep3580 !

I just tried the library on the [demo project](https://github.com/lbertenasco/ng-emoji-picker-demo) and it's working fine with `Angular: 5.2.1`.

Please check the repo and let me know if it helps.

Feel free to re-open this issue if you have more information on the issue.

**Comment by Johndeep3580** [comment]
U saved me bro..Just another thing I want to ask that I am using this emoji input to send data to mobile devices so will all mobile devices be able to decode this emoji or can I get the unicode format of the  emoji somehow?

**Comment by lbertenasco** [comment]
The input you are sending is the emoji code, most of the devices will be able to display the emoji.
But I'm not sure about really old devices.
Sadly you'll need to test this yourself.

Here you can find all the available emojis:
https://raw.githubusercontent.com/lbertenasco/ng-emoji-picker/master/src/emoji.db.ts

**Comment by Johndeep3580** [comment]
class with input field in your case red is not showing any change in input field

**Comment by SebastianGiro** [comment]
@Johndeep3580 you will need to check some css guides about flexbox and positioning in general. Your problem lacks in css I think
