### ISSUE TITLE
Keep popup open after add icon

### ISSUE THREAD

**Issue by franbueno** [lbertenasco/ng-emoji-picker#17]
Its very painful if you want to add many icons 😣

I think it might be optional so handle event after select the icon.

Thanks! and congratulations! <3

**Comment by lbertenasco** [comment]
Hi @franbueno , thanks for the kind words!

I just released Version `1.2.4` that has an input option called `closeAfterSelection`.

If you set it to `false` it will behave as what you requested.

Please check the documentation and the [demo project](https://github.com/lbertenasco/ng-emoji-picker-demo) if you need more information.

Feel free to re-open this issue if you find any issues with the new version.
