### ISSUE TITLE
@angular/core ngDevMode error in Angular 6

### ISSUE THREAD

**Issue by AhmadAdel93** [lbertenasco/ng-emoji-picker#21]
It doesnt have Angular 6 support , so it installs a node_modules folder which would give this error:
"
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng-emoji-picker/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
"

**Comment by gangakore** [comment]
Me too facing the same issue.

**Comment by raDiesle** [comment]
+1

**Comment by hkkhchan** [comment]
+1

**Comment by lbertenasco** [comment]
Just released a new version that supports angular6
`npm install ng-emoji-picker@6.0.0 --save`
