### ISSUE TITLE
Emoji popup not close on outside click event 

### ISSUE THREAD

**Issue by sagaraher** [lbertenasco/ng-emoji-picker#22]
when I would click on emoji , I open popup with all emoji but when I will click on browser area or within the same component this dialog is still open . I want this to be closed after click out side .

**Comment by dkaushikl** [comment]
Have you found any solution?

**Comment by lbertenasco** [comment]
Hi @sagaraher @dkaushikl !
This is not an issue of the package.
If you want to add functionality to it feel free to submit a pull request 😄 
Cheers!
