### ISSUE TITLE
ngDevMode Error in Angular 7

### ISSUE THREAD

**Issue by kkrishnakv** [lbertenasco/ng-emoji-picker#32]
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng-emoji-picker/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by raDiesle** [comment]
Same with 6.0.3 

 "@angular-devkit/build-angular": "~0.6.3",
    "@angular-devkit/build-optimizer": "^0.6.3",
    "@angular/cli": "6.0.5",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.7",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.1.2",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.0",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "node-sass": "^4.9.0",
    "protractor": "^5.3.2",
    "protractor-testability-plugin": "^1.2.0",
    "testcafe": "0.23.3",
    "testcafe-angular-selectors": "0.3.1",
    "ts-node": "~6.0.3",
    "tslint": "~5.10.0",
    "typescript": "^2.7.2"

**Comment by Aviking88** [comment]
Same with 6.1.0

**Comment by lbertenasco** [comment]
Hey @Aviking88 , This library is not supported anymore (not working for angular v >6 . check the readme please)

I'm closing the issue :)

**Comment by Aviking88** [comment]
> Hey @Aviking88 , This library is not supported anymore (not working for angular v >6 . check the readme please)
> 
> I'm closing the issue :)



Thanks @lbertenasco ,
can you suggest any alternatives?
