### ISSUE TITLE
Clean input

### ISSUE THREAD

**Issue by Lisa159** [lbertenasco/ng-emoji-picker#34]
Hi! I am using your emoji picker for a chat app but I am having trouble to clean input after sending text. Any ideas how to clean it?
I did it like this way:
` (<HTMLInputElement>document.getElementsByClassName("emojiInput")[0]).value = "";`
But it is not working good, it's not totally cleaning the input.

**Comment by Lisa159** [comment]
Sorry for the inconveniences, error solved. :)

**Comment by mkhanzapoj** [comment]
good
