### ISSUE TITLE
emoji look black & white in chorme

### ISSUE THREAD

**Issue by shifa-jain** [lbertenasco/ng-emoji-picker#35]
i have use this lib "ng-emoji-picker" in my app.The problem is ,lib is working fine in firfox but not in chorme emoji are showing black and white

**Comment by lbertenasco** [comment]
I'm sure it has to do with something related to the browser version and the os you are using.
Since this is not a problem with the library I'll close the issue but feel free to continue commenting or re-opening the issue if something else comes up.

**Comment by shifa-jain** [comment]
![chorme](https://user-images.githubusercontent.com/46775551/63419950-588c4d00-c423-11e9-9ded-8d5d02253e24.png)
![chorme](https://user-images.githubusercontent.com/46775551/63420050-8b364580-c423-11e9-8007-d8e856af34bd.png)
