### ISSUE TITLE
Updated the version of chorme still get black & white emoji 

### ISSUE THREAD

**Issue by shifa-jain** [lbertenasco/ng-emoji-picker#36]
currently I am using
this versions:

 Angular:- 4.2.4
ng-emoji-picker":- "1.1.13",
Google-chorme: 76.0.3809.100 (Official Build) (64-bit)

still getting this in chrome

![chormeEmoji](https://user-images.githubusercontent.com/46775551/63420878-3abfe780-c425-11e9-8931-00f91fc1f58d.png)

**Comment by lbertenasco** [comment]
Hey @shifa-jain This has nothing to do with the library. It depends on how does the browser and Operating System handle emojis. (those are the universal ascii codes for the emojis, you can only see them as colored emojis if your system automatically replaces them with the emoji image)
