### ISSUE TITLE
Unable to used Emoji  in Angular8

### ISSUE THREAD

**Issue by WaleedAshrafUsmani** [lbertenasco/ng-emoji-picker#39]
I am getting error when i serve my project on the component where i used emoji
"StaticInjectorError(AppModule)[NgForOf -> ViewContainerRef]: 
  StaticInjectorError(Platform: core)[NgForOf -> ViewContainerRef]: 
    NullInjectorError: No provider for ViewContainerRef!"

When i try to build in prod
I am getting that error
ERROR in ../ng-emoji-picker/emoji-picker.module.ts(8,2): Error during template compile of 'EmojiPickerModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
Kindly Check that issue i was used in project before angular8 is working great let me  know whats the issue.

My Package.json file:
  "dependencies": {
    "@angular-devkit/build-angular": "^0.803.19",
    "@angular-devkit/build-webpack": "^0.803.19",
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/fire": "^5.2.3",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^8.2.14",
    "@angular/http": "^6.0.3",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@ctrl/ngx-emoji-mart": "^1.0.3",
    "@ng-bootstrap/ng-bootstrap": "^2.2.0",
    "@ngrx/store": "^8.5.2",
    "@ngui/map": "^0.20.1",
    "@types/googlemaps": "^3.38.0",
    "ammap3": "^3.21.13",
    "angular-archwizard": "^3.0.0",
    "angular-datatables": "^5.0.0",
    "angular-emoji-picker-extended": "^0.3.8",
    "angular-notification-icons": "^1.0.0",
    "angular2-moment": "^1.7.0",
    "ap-angular-fullcalendar": "1.6.4",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.9.3",
    "core-js": "^2.6.10",
    "d3": "3.5.6",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "emoji-mart": "^2.11.1",
    "emojionearea": "^3.4.1",
    "firebase": "^7.5.0",
    "form-serialize": "^0.7.2",
    "fullcalendar": "3.6.1",
    "hammerjs": "^2.0.8",
    "i": "^0.3.6",
    "imagesloaded": "^4.1.3",
    "jquery": "^3.4.1",
    "moment": "^2.19.1",
    "ng-emoji-picker": "^6.0.1",
    "ng-inline-svg": "^9.1.0",
    "ng-selectize": "^1.1.1",
    "ng2-charts": "^1.6.0",
    "ng2-nouislider": "1.7.6",
    "ng2-nvd3": "^2.0.0",
    "ng2-scroll-to": "^1.0.7",
    "ng2-sticky-kit": "5.0.0",
    "ng2-toasty": "^4.0.3",
    "ng2-validation": "^4.2.0",
    "ngx-masonry": "^1.1.2",
    "ngx-mat-select-search": "^1.8.0",
    "ngx-perfect-scrollbar": "^5.3.5",
    "nouislider": "^10.1.0",
    "npm": "^6.13.1",
    "npm-upgrade": "^2.0.2",
    "nvd3": "^1.8.6",
    "pace-js": "^1.0.2",
    "popper.js": "^1.16.0",
    "rxjs": "6.5.3",
    "rxjs-compat": "^6.2.1",
    "selectize": "^0.12.4",
    "sweetalert2": "^7.1.2",
    "wdt-emoji-bundle": "^0.2.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/core": "^8.3.19",
    "@angular/cli": "^8.3.19",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/bootstrap": "^4.3.1",
    "@types/datatables.net": "^1.10.18",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.13.0",
    "protractor": "^6.0.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.4.5"
  }

**Comment by lbertenasco** [comment]
There is NO Support for Angular 8
