### ISSUE TITLE
'emoji-input' is not a known element

### ISSUE THREAD

**Issue by VickNet** [lbertenasco/ng-emoji-picker#5]
I've followed these steps: install and add to app.module file as import.
When I want to use it, I got this error:

> Uncaught Error: Template parse errors:
> 'emoji-input' is not a known element:
> 1. If 'emoji-input' is an Angular component, then verify that it is part of this module.
> 2. If 'emoji-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 

I need to import something in the .ts file where I use this element?

**Comment by lbertenasco** [comment]
Hi @VickNet !
Add this to your **app.module**

```typescript
import {NgModule, CUSTOM_ELEMENTS_SCHEMA} from "@angular/core";

...
schemas: [CUSTOM_ELEMENTS_SCHEMA]
...
```

**Comment by VickNet** [comment]
Added, but still not working.
http://i.imgur.com/4Khv7xw.png

**Comment by lbertenasco** [comment]
What version of angular are you using?
`ng -v`

**Comment by VickNet** [comment]
![image](https://user-images.githubusercontent.com/11840533/28033662-9deadab4-65b7-11e7-8c29-55a2eb19448e.png)

**Comment by lbertenasco** [comment]
Ok, could you please paste the content of the files where you are importing/using `ng-emoji-picker`?
It's probably a quick fix but without seeing the code it's hard to guess 😅

**Comment by VickNet** [comment]
In app module I have imported EmojiPickerModule:
`import { EmojiPickerModule } from "ng-emoji-picker";`
and inserted EmojiPickerModule in _imports_ array.
After this, I start use `<emoji-input></emoji-input>` in my project.

**Comment by lbertenasco** [comment]
Ok, just tried it on a brand new **ng** project and it works fine.
You can check it out here: `https://github.com/lbertenasco/ng-emoji-picker-demo`
PD: I always use [yarn](https://yarnpkg.com/en/) instead of `npm`

**Comment by ChamaraPhilipsuom** [comment]
Same happens to me with angular 5. Is this a problem when using npm? Little confused about this.

**Comment by HareendraChamara** [comment]
My bad. It works fine. I tried to put the openPopup in the constructor. It should be declared just as in the [demo](https://github.com/lbertenasco/ng-emoji-picker-demo) Awesome work @lbertenasco

**Comment by ChamaraPhilipsuom** [comment]
My bad. It works fine. I tried to put the openPopup in the constructor. It should be declared just as in the demo Awesome work @lbertenasco

But now it gives an udefined infront of the text. Also can't we give styles to the textbox. And avoid appending smilies.

**Comment by lbertenasco** [comment]
Hi @ChamaraPhilipsuom, thanks!
Can you please create a new ticket with your issue and add as much details about it as possible?
I'll check it out when I have a bit of free time :)

**Comment by WassimSlim21** [comment]
Hello, I downloaded your project, it works, i want to do the same think in my project, but the different thing that i'm using a popup, so got this error, 
StaticInjectorError(AppModule)[NgForOf -> ViewContainerRef]: 
  StaticInjectorError(Platform: core)[NgForOf -> ViewContainerRef]: 
    NullInjectorError: No provider for ViewContainerRef!
