### ISSUE TITLE
Picker usage?

### ISSUE THREAD

**Issue by turbo5** [lbertenasco/ng-emoji-picker#7]
I'm not sure whether this is a bug or the lack of documentation.
I'm on windows8, ng-emoji-picker@1.1.13, latest chrome.
Can you include an example what includes using the popup?
I added the example provided into my app, and the shortcodes (well, some of them) work inside the textarea, like :smile:, they are shown, but I don't see the button which should open the picker, nor do I know how to open the picker itself. 
Expected functioning is to have an opener icon at the end of the input (textarea), which opens the picker/searcher, as it is in the base repo's demo: https://antewall.github.io/angular2-emoji/

**Comment by lbertenasco** [comment]
Hi @turbo5 !
Can you add a snippet of the your code? Both .html and .ts files so I can properly help you 🙂
Thanks!

**Comment by turbo5** [comment]
Okay, related snippets are
```
<emoji-input class="editor"
                        [(model)]="story.content"
                        [textArea]="{cols: 40, rows: 5}"
                        [popupAnchor]="'bottom'"
                        (setPopupAction)="setPopupAction($event)">
          </emoji-input>
```
```
export class StoryWriteComponent extends BaseComponent{
  @Input() story: Story;
  public openPopup: Function;
  setPopupAction(fn: any) {
    this.openPopup = fn;
  }

```
Thank you!

**Comment by lbertenasco** [comment]
In your html you can add:
```
<button (click)="openPopup(true)">
  :)
</button>
```
Let me know if this helps!

**Comment by turbo5** [comment]
Thanks, that worked. One more question: I actually have 2 instances of this on the page, with two different models ofc. How can I specify in which textarea to use with the popup?

**Comment by lbertenasco** [comment]
You can change the `(setPopupAction)="setPopupAction($event)" ` to set a custom event for each of your instances: i.e.:
```
(setPopupAction)="setPopupAction1($event)"
...
setPopupAction1(fn: any) {
    this.openPopup1 = fn;
  }

----

(setPopupAction)="setPopupAction2($event)"
...
setPopupAction2(fn: any) {
    this.openPopup2 = fn;
  }

```

**Comment by turbo5** [comment]
Thanks a lot! Now I could make it work with both.

One thing I had to add when using two separate pickers is to add position: relative to the .emoji-search css class (with !important) for both to be positioned properly to their opener buttons respectively.
You might consider to include this solution properly in your code, after checking.

Cheers!

**Comment by lbertenasco** [comment]
Great! I'll check it out thanks!
