### ISSUE TITLE
icon relaxed in not working

### ISSUE THREAD

**Issue by guyPolitzer** [lbertenasco/ng-emoji-picker#8]
when i click the relaxed icon I get black smiley face not '😌'

**Comment by lbertenasco** [comment]
Hi @guyPolitzer !
Just tried it out on a new project and it's working fine.
Can you share more details on this issue?

**Comment by guyPolitzer** [comment]
i had implement it via "npm ng2-emoji-picker"
the relaxed icon appearing good, it shows as black and white smelly face not the yellow icon,

**Comment by lbertenasco** [comment]
`npm ng2-emoji-picker` is not this package though.
