### ISSUE TITLE
Unexpected value 'EmojiPickerModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by HimanshuSojitra** [lbertenasco/ng-emoji-picker#9]
I see the below error in Google Chrome console after importing the package in app.module.ts file and `ng-serve` - ing the app:
**Unexpected value 'EmojiPickerModule' imported by the module 'AppModule'. Please add a @NgModule annotation.**

Is it related to the version? This is how my package.json looks like currently:
**package.json**

`{
	"name": "my-app",
	"version": "0.0.0",
	"license": "MIT",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e"
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "^5.0.0",
		"@angular/common": "^5.0.0",
		"@angular/compiler": "^5.0.0",
		"@angular/core": "^5.0.0",
		"@angular/forms": "^5.0.0",
		"@angular/http": "^5.0.0",
		"@angular/platform-browser": "^5.0.0",
		"@angular/platform-browser-dynamic": "^5.0.0",
		"@angular/router": "^5.0.0",
		"angularfire2": "^5.0.0-rc.4",
		"core-js": "^2.4.1",
		"file-saver": "^1.3.3",
		"firebase": "^4.7.0",
		"ng-emoji-picker": "^1.1.13",
		"ng2-page-scroll": "^4.0.0-beta.12",
		"rxjs": "^5.5.2",
		"zone.js": "^0.8.14"
	},
	"devDependencies": {
		"@angular/cli": "1.5.4",
		"@angular/compiler-cli": "^5.0.0",
		"@angular/language-service": "^5.0.0",
		"@types/jasmine": "~2.5.53",
		"@types/jasminewd2": "~2.0.2",
		"@types/node": "~6.0.60",
		"codelyzer": "^4.0.1",
		"jasmine-core": "~2.6.2",
		"jasmine-spec-reporter": "~4.1.0",
		"karma": "~1.7.0",
		"karma-chrome-launcher": "~2.1.1",
		"karma-cli": "~1.0.1",
		"karma-coverage-istanbul-reporter": "^1.2.1",
		"karma-jasmine": "~1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "~5.1.2",
		"ts-node": "~3.2.0",
		"tslint": "~5.7.0",
		"typescript": "~2.4.2"
	}
}
`

Thank you for this awesome package! :)

**Comment by lbertenasco** [comment]
Hi @HimanshuSojitra !
Thanks for the kind words :)
It should be fixed by upgrading `ng-emoji-picker` to version `1.2.0`.
Feel free to re-open the issue.
